apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  annotations:
    external-dns.alpha.kubernetes.io/hostname: nginx.external-dns-test.rashendra.com
  labels:
    env: dev
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    env: dev